import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: any
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>   
        <div style={{display:"flex", margin:"20px"}}>  
        {children}
        </div>  
      </body>
    </html>
  );
}
